name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      (
        github.event.action == 'closed' ||
        (
          github.event.action == 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'backport')
        )
      )
    steps:
      - uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.MY_PAT }}
          
      - name: Find Backport PR URL
        id: find_pr
        run: |
          ORIGINAL_PR_NUMBER=${{ github.event.pull_request.number }}
          TARGET_BRANCH="new1" # Adjust this line as needed to dynamically determine the target branch.
          HEAD_BRANCH="backport-${ORIGINAL_PR_NUMBER}-to-${TARGET_BRANCH}"
          PR_URL=$(gh pr list --head "$HEAD_BRANCH" --repo ${{ github.repository }} --json url --jq '.[0].url')
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
          
      - name: Comment on Original PR with Backport PR Link
        if: env.PR_URL != ''
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.MY_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Backported changes are available in this PR: ${{ env.PR_URL }}
