name: Backport

on:
  pull_request:
    types: [closed]

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Determine Target Branch
        id: target_branch
        run: |
          echo "Determining target branch..."
          echo "TARGET_BRANCH=new1" >> $GITHUB_ENV
      - name: Backport to Determined Branch
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.MY_PAT }}
          title_template: "[Backport {{base}}] {{originalTitle}}"
        env:
          TARGET_BRANCH: ${{ env.TARGET_BRANCH }}
