name: Backport

on:
  pull_request:
    types: [closed]

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport')
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
      
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
      - name: Cherry-pick commit and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          # Assuming you want to backport to branch "new1"
          git fetch origin
          git checkout -b backport-branch-name origin/new1
          git cherry-pick YOUR_COMMIT_SHA_HERE
          
          # Push backport branch
          git push origin backport-branch-name
          
          # Create pull request
          gh pr create --base new1 --head backport-branch-name --title "Backport PR Title" --body "Backport PR description"
