name: Backport

on:
  pull_request:
    types: [closed, merged]

jobs:
  backport:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Backport to npe branch
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.MY_PAT }}
          target_branch_prefix: "new1"
          pull_request_labels: "backport"
