name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      (
        github.event.action == 'closed' ||
        (
          github.event.action == 'labeled' &&
          contains(github.event.pull_request.labels.*.name, 'backport')
        )
      )
    steps:
      - uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.MY_PAT }}
