name: Post Latest Merged PR to Slack

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  post-latest-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Latest Merged PR
      id: get_latest_pr
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.request('GET /repos/{owner}/{repo}/pulls', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed',
            base: 'main', // or whatever your base branch is
            per_page: 1, // Limit to 1 PR
            page: 1, // Get the first page
            sort: 'updated', // Sort by updated time to get the latest PR
            direction: 'desc' // Get the most recent PR
          });
          const latestPR = response.data[0];
          const prInfo = `- ${latestPR.title} (#${latestPR.number}) by ${latestPR.user.login}: ${latestPR.html_url}`;
          console.log(prInfo);
          core.setOutput('latest_pr_info', prInfo);

    - name: Post to Slack
      if: always() # This step should always run, regardless of whether the PR is merged
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: '#random' # Specify the channel where you want to post the message
      run: |
        PR_INFO=$(echo "${{ steps.get_latest_pr.outputs.latest_pr_info }}")
        JSON="{\"text\": \"Latest Merged Pull Request:\n$PR_INFO\", \"channel\": \"$SLACK_CHANNEL\"}"
        curl -X POST -H 'Content-type: application/json' --data "$JSON" $SLACK_WEBHOOK_URL
