name: Post Merged PRs to Slack

on:
  pull_request:
    types: [closed]

jobs:
  post-merged-prs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Latest Merged PR
      id: get_latest_pr
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.request('GET /repos/{owner}/{repo}/pulls', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'closed',
            sort: 'updated',
            direction: 'desc',
            per_page: 1
          });
          const latestPR = response.data[0];
          if (latestPR.merged_at) {
            const prInfo = `- ${latestPR.title} (#${latestPR.number}) by ${latestPR.user.login}: ${latestPR.html_url}`;
            console.log(prInfo);
            core.setOutput('merged_pr_info', prInfo);
          } else {
            core.setOutput('merged_pr_info', ''); // If no merged PRs found, set output to empty string
          }

    - name: Post to Slack
      if: steps.get_latest_pr.outputs.merged_pr_info != '' # Only run if there are merged PRs
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: '#test' 
      run: |
        PR_INFO=$(echo "${{ steps.get_latest_pr.outputs.merged_pr_info }}")
        JSON="{\"text\": \"Merged Pull Request:\n$PR_INFO\", \"channel\": \"$SLACK_CHANNEL\"}"
        curl -X POST -H 'Content-type: application/json' --data "$JSON" $SLACK_WEBHOOK_URL
