name: PR Test, Deploy and Canary Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - 'master' # Adjust this to include the branches where you want this workflow to run

jobs:
  test-on-pr-approval:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test on Test Machines
        run: |
          echo "Running tests on test machines..."
      
          # Insert your command to run tests on the test machines
          # For example, using salt-ssh or another tool to execute your tests

  deploy-and-test-canary:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    needs: test-on-pr-approval
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Canary Machines
        env:
          CANARY_MACHINES: ${{ secrets.CANARY_MACHINES }}
        run: |
          echo "Deploying to canary machines: $CANARY_MACHINES"
          # Replace this with your deployment command, e.g., salt-ssh
          # Ensure you parse CANARY_MACHINES if it's a list
      
      - name: Debug Environment Variables
        run: env    

      - name: Run Tests on Canary Machines
        env:
          CANARY_MACHINES: ${{ secrets.CANARY_MACHINES }}
        run: |
          echo "Running tests on canary machines: ...."
          IFS=', ' read -r -a machines <<< "${CANARY_MACHINES}"
          for machine in "${machines[@]}"; do
            echo "$machine"
          done

      - name: Post Test Results to PR
        uses: actions/github-script@v5
        if: always()
        with:
          script: |
            const deploymentStatus = '${{ job.status }}';
            const message = deploymentStatus === 'success'
              ? '🟢 Canary deployment and tests completed successfully.'
              : '🔴 Canary deployment and tests failed. Check the logs for details.';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            })
